CREATE TABLE List (
ListID BIGINT IDENTITY (1,1) PRIMARY KEY,
Subject VARCHAR(255),
Description VARCHAR(255),
Date DATE,
Time TIME,
userID BIGINT FOREIGN KEY REFERENCES users(userID)
);

CREATE TABLE users (
  userID BIGINT IDENTITY (1,1) PRIMARY KEY,
  username VARCHAR(255) NULL,
  password VARCHAR(255) NULL
);
